// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    // Migrations (migrate deploy / dev) must use a DIRECT, non-pooled connection.
    // Neon's pooled endpoint (PgBouncer) does not support the session-level
    // advisory locks Prisma Migrate relies on. Set DIRECT_URL to the unpooled
    // Neon host for migrations; the app runtime still uses the pooled DATABASE_URL
    // via the driver adapter (src/lib/prisma.ts). Falls back to DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
